# Example Site settings

google_analytics: UA-35910281-31

header_pages:
  - index.md
  - chinese.md
  - spanish.md
  - arabic.md
  - portuguese.md
  - french.md
  - russian.md
  - japanese.md
  - german.md
  - korean.md
      

#footer: 'insert social media'

#style: light # dark (default) or light
#listen_for_clients_preferred_style: true # true or false (default)

plugins:
  - jekyll-seo-tag
