# Example Site settings

google_analytics: UA-35910281-31

header_pages:
  - index.md
  - chinese.md
  - spanish.md
  - arabic.md
  - portuguese.md
  - french.md
  - russian.md
  - japanese.md
  - german.md
  - korean.md
      

footer: 
  '<a href="https://www.facebook.com/scenographist/"><img src="https://github.com/Scenographist/scenographist/blob/a2fa13fa4f123bd36a88223ee18a2d97034a9ef8/images/social/facebook.svg"></a>'
  '<a href="https://twitter.com/generatedart"><img src="https://github.com/Scenographist/scenographist/blob/a2fa13fa4f123bd36a88223ee18a2d97034a9ef8/images/social/twitter.svg"></a>'
  '<a href="https://www.instagram.com/generatedart/"><img src="https://github.com/Scenographist/scenographist/blob/a2fa13fa4f123bd36a88223ee18a2d97034a9ef8/images/social/instagram.svg"></a>'
  '<a href="https://www.youtube.com/@scenographist"><img src="https://github.com/Scenographist/scenographist/blob/a2fa13fa4f123bd36a88223ee18a2d97034a9ef8/images/social/youtube.svg"></a>'
  '<a href="https://www.tiktok.com/@generatedart"><img src="https://github.com/Scenographist/scenographist/blob/a2fa13fa4f123bd36a88223ee18a2d97034a9ef8/images/social/tiktok.svg"></a>'

#style: light # dark (default) or light
#listen_for_clients_preferred_style: true # true or false (default)

plugins:
  - jekyll-seo-tag
